name: Terminus Conversion Tools Plugin
on:
  push:
  workflow_dispatch:
    inputs:
      functional_tests_are_enabled:
        description: Include functonal tests
        required: true
        default: 1
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
      - name: Install dependencies
        run: composer install
      - name: Validate code
        run: composer cs
      - name: Run unit tests
        run: composer tests:unit

  functional_tests:
    if: ${{ github.ref == 'refs/heads/main' || github.event.inputs.functional_tests_are_enabled == 1 }}
    needs: [ build ]
    strategy:
      matrix:
        testing_groups:
          - name: on drops-8 upstream
            group: upstream:drops8
          - name: on empty upstream
            group: upstream:empty
          - name: on drupal-project upstream
            group: upstream:drupal-project
          - name: advise command scenarios on empty upstream
            group: advise-scenarios:empty
      fail-fast: false
    runs-on: ubuntu-latest
    name: Testing ${{ matrix.testing_groups.name }}
    env:
      TERMINUS_TEST_SITE_DROPS8_UPSTREAM_ID: ${{ secrets.TERMINUS_TEST_SITE_DROPS8_UPSTREAM_ID }}
      TERMINUS_TEST_SITE_EMPTY_UPSTREAM_ID: ${{ secrets.TERMINUS_TEST_SITE_EMPTY_UPSTREAM_ID }}
      TERMINUS_TEST_SITE_DRUPAL_RECOMMENDED_UPSTREAM_ID: ${{ secrets.TERMINUS_TEST_SITE_DRUPAL_RECOMMENDED_UPSTREAM_ID }}
      TERMINUS_ORG: ${{ secrets.TERMINUS_ORG }}
      TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
      - name: Install dependencies
        run: composer install
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TERMINUS_SITE_OWNER_SSH_PRIVATE_KEY }}
      - name: Setup Git username and email
        run: |
          git config --global user.email "${{ secrets.TERMINUS_USER_EMAIL }}"
          git config --global user.name "${{ secrets.TERMINUS_USER_NAME }}"
      - name: Install and build Terminus
        run: |
          mkdir ../terminus-source && cd ../terminus-source
          composer create-project pantheon-systems/terminus . ^3 --stability=dev
          composer phar:build
          rsync -r --copy-links . ..
          rm -rf ../terminus-source
      - name: Install plugin from local path
        working-directory: ..
        run: |
          ./terminus self:plugin:install terminus-conversion-tools-plugin
          ./terminus self:plugin:list
          ./terminus conversion:composer -h
      - name: Run functional tests
        working-directory: ../terminus-conversion-tools-plugin
        run: composer tests:functional:group:${{ matrix.testing_groups.group }}
