name: Terminus Conversion Tools Plugin
on: push
jobs:
  infrastructure_setup:
    runs-on: ubuntu-latest
    name: Prepare infrastructure
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
      - name: Setup Git username and email
        run: |
          git config --global user.email "${{ secrets.TERMINUS_USER_EMAIL }}"
          git config --global user.name "${{ secrets.TERMINUS_USER_NAME }}"
      - name: Install dependencies
        run: composer install
      - name: Validate code
        run: composer cs
      - name: Save repo content as artifact
        uses: actions/upload-artifact@v2
        with:
          name: full-workspace
          path: ${{ github.workspace }}

  unit_tests:
    runs-on: ubuntu-latest
    name: Unit tests
    needs: [ infrastructure_setup ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: full-workspace
      - name: Run unit tests
        run: composer tests:unit

  functional_tests:
    runs-on: ubuntu-latest
    name: Functional tests
    needs: [ infrastructure_setup ]
    env:
      TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
      TERMINUS_SITE: ${{ secrets.TERMINUS_SITE }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: full-workspace
      - name: Install and build Terminus
        run: |
          mkdir ../terminus-source && cd ../terminus-source
          composer create-project pantheon-systems/terminus . dev-cms-232-debug-t3-auth-issue --stability=dev
          composer phar:build
          rsync -r --copy-links . ..
          rm -rf ../terminus-source
      - name: Install the plugin
        working-directory: ..
        run: |
          ./terminus self:plugin:install terminus-conversion-tools-plugin
          ./terminus self:plugin:list
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TERMINUS_SITE_OWNER_SSH_PRIVATE_KEY }}
      - name: Run functional tests
        working-directory: ../terminus-conversion-tools-plugin
        run: composer tests:functional
